// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        pgtype.UUID
	Username  string
	Email     string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type AccountInformation struct {
	ID             pgtype.UUID
	DisplayName    string
	FavoriteNumber pgtype.Int4
	HomeworldRealm pgtype.Text
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
	DeletedAt      pgtype.Timestamp
	AccountID      pgtype.UUID
}

type AccountRole struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	UserRoleID pgtype.UUID
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

type Project struct {
	ID        pgtype.UUID
	Title     string
	Sector    string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type ProjectAccountAssignment struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	AccountID pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type UserRole struct {
	ID        pgtype.UUID
	RoleTitle string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
